### ISSUE TITLE
add_key_code(NUM) → unexpected hold_down_milliseconds in output

### ISSUE THREAD

**Issue by AdamWagner** [sdondley/JSON-Karabiner#2]
When a number keycode is specified as a `to` action, an unexpected `hold_down_milliseconds` is added to the definition, which, in my example, makes the combination impossible to press.

If I replace `add_key_code('9')` with `add_key_code('hyphen')`, the output does not include `hold_down_milliseconds`, and everything works as expected.

**Input**

```
# Tell the "to" action what to do
add_key_code('9');
```

**Output**

```
"to" : [
  {
     "hold_down_milliseconds" : "9",
     "key_code" : "9"
  }
]
```

PS – thank you for your effort, this project makes it much nicer to manage complex rules. Previously I was generating rules from a JS file with tons of custom wrapper functions. I don't think I'll need to maintain that anymore ;-)

**Comment by sdondley** [comment]
OK, thanks for the report and helping kick the tires of this new code. I can successfully reproduce with this code:

```
set_title 'some title';
set_rule_name 'some rule name';

new_manipulator;

add_action 'from';
add_key_code 'a';
add_action 'to';
add_key_code '9';

write_file();
```

Seems to only happen with numbers. It probably happens as a result of some new code that ensured integer values were not surrounded by quotes.

At any rate, I will get this fixed this weekend, possibly today.

**Comment by sdondley** [comment]
OK, found the issue. One little missing hyphen was the problem.

Will upload a new version shortly.

**Comment by AdamWagner** [comment]
That was .... insanely fast. 👍
