### ISSUE TITLE
Ç to Enter key

### ISSUE THREAD

**Issue by susie132** [sdondley/JSON-Karabiner#6]
Hi. I have absolutely no experience with coding hence asking for help here. All I want to do is change the main Ç or ç button to act as the Enter key. I don´t want the Ç/ç key to work at all as that, only an Enter key. 

From my research, I believe the Ç is named as "_non_us_backslash_", but I could be wrong, of course. 

I have a QWERTY Spanish/Catalan keyboard. The Ç key is right next to the normal Enter button (see pic below) and I keep hitting it by accident so I want it to act as Enter as well. 

I have tried inputting the following code into the JSON file, saved and quitted/restarted the Karabiner app several times, but no success. I took the below code from the Copilot AI browser. 

Are there other options I should be looking at within the whole Karabiner app, or just the above? 

Please can you help? Thank you. 

> {
>     "description": "Ç to Enter",
>     "manipulators": [
>         {
>             "from": { "key_code": "non_us_backslash" },
>             "to": [{ "key_code": "return_or_enter" }],
>             "type": "basic"
>         }
>     ]
> }

![imagen](https://github.com/sdondley/JSON-Karabiner/assets/165213637/fa07ad0d-0c30-41a8-9bec-7b35ff9e83d0)

**Comment by sdondley** [comment]
Use the "event viewer" app that comes with karabiner to determine the key code for Ç

**Comment by susie132** [comment]
> Use the "event viewer" app that comes with karabiner to determine the key code for Ç

Thank you!! It's working now :)
